#!/bin/bash
set -e

echo '\documentclass[preview]{standalone}
\usepackage{blindtext}
%\usepackage[utf8]{inputenc}
\usepackage{tikz}
\usepackage{tikz-uml}
%\usepackage{pgf-umlsd}
\usetikzlibrary{
  angles,
  arrows,
  backgrounds,
  calc,
  chains,
  decorations,
  decorations.pathmorphing,
  decorations.pathreplacing,
  decorations.text,
  fit,
  positioning,
  quotes,
  shapes.arrows,
  shapes.geometric,
  shapes.symbols,
}

\usepackage{fontspec}
\setsansfont{Verdana}
\begin{document}'
cat "$1"
echo '\end{document}'
